name: doggobox
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3
  equatable: ^1.2.4
  meta: ^1.2.3
  rxdart: ^0.24.1
  video_player:  ^0.10.12+2
  confetti: ^0.5.4+1
  stripe_payment: ^1.0.7
  stripe_sdk: ^3.0.1+1
  http: ^0.12.2
  credit_card_number_validator: ^1.0.4
  firebase_analytics: ^5.0.2
  firebase_auth: ^0.18.0+1
  cloud_firestore: ^0.14.0+2
  url_launcher: ^5.5.3
  js: ^0.6.2

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  fonts:
    - family: SF Pro
      fonts:
        - asset: fonts/SF-Pro.ttf
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/apple_pay.png
    - assets/apple_pay_2x.png
    - assets/apple_pay_3x.png
    - assets/dog_holding_toy.png
    - assets/dog_holding_toy_2x.png
    - assets/dog_holding_toy_3x.png
    - assets/doggo_box.png
    - assets/doggo_box_2x.png
    - assets/doggo_box_3x.png
    - assets/doggo_shop_logo.png
    - assets/doggo_shop_logo_2x.png
    - assets/doggo_shop_logo_3x.png
    - assets/doggo_with_toys.png
    - assets/doggo_with_toys_2x.png
    - assets/doggo_with_toys_3x.png
    - assets/dog_and_box.png
    - assets/dog_and_box_2x.png
    - assets/dog_and_box_3x.png
    - assets/dog_and_box_desktop.png
    - assets/dog_and_box_desktop_2x.png
    - assets/dog_and_box_desktop_3x.png
    - assets/badge.png
    - assets/badge_2x.png
    - assets/badge_3x.png
    - assets/badge_desktop.png
    - assets/badge_desktop_2x.png
    - assets/badge_desktop_3x.png
    - assets/dog_chewing_toy.png
    - assets/dog_chewing_toy_2x.png
    - assets/dog_chewing_toy_3x.png
    - assets/doggo_box_contents.png
    - assets/doggo_box_contents_2x.png
    - assets/doggo_box_contents_3x.png
    - assets/sample_dog_1.png
    - assets/sample_dog_1_2x.png
    - assets/sample_dog_1_3x.png
    - assets/sample_dog_2.png
    - assets/sample_dog_2_2x.png
    - assets/sample_dog_2_3x.png
    - assets/sample_dog_3.png
    - assets/sample_dog_3_2x.png
    - assets/sample_dog_3_3x.png
    - assets/dog_party.png
    - assets/dog_party_2x.png
    - assets/dog_party_3x.png
    - assets/credit_cards.png
    - assets/credit_cards_2x.png
    - assets/credit_cards_3x.png
    - assets/sample_dog_banner_1.png
    - assets/sample_dog_banner_1_2x.png
    - assets/sample_dog_banner_1_3x.png
    - assets/sample_dog_banner_2.png
    - assets/sample_dog_banner_2_2x.png
    - assets/sample_dog_banner_2_3x.png
    - assets/sample_dog_banner_3.png
    - assets/sample_dog_banner_3_2x.png
    - assets/sample_dog_banner_3_3x.png
    - assets/stamp.png
    - assets/stamp_2x.png
    - assets/stamp_3x.png
    - assets/dog_napping.png
    - assets/dog_napping_2x.png
    - assets/dog_napping_3x.png
    - assets/dog_water_bottle.png
    - assets/dog_water_bottle_2x.png
    - assets/dog_water_bottle_3x.png
    - assets/dog_water_bottle_2.png
    - assets/dog_water_bottle_2_2x.png
    - assets/dog_water_bottle_2_3x.png
    - assets/dogs_excited.gif
    - assets/dog_drinking_water.mov

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
